# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_v0SKhn2F_Gid2K7vUA_G7UHgKA-JUfT
"""

n = int(input())
count = 0
for i in range (1,n):
    if n % i == 0:
        count += i

if count == n:
    print("Yes")

else :
    print("No")